// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrvjethlrrupiuyfhohi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndydmpldGhscnJ1cGl1eWZob2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTA1NzEsImV4cCI6MjA2NzYyNjU3MX0.kS6sgHxZxeAA8qiT7KXnL00cRBLQoExlnuqlJ0JJWdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});